import Link from "next/link";
import { ArrowRight, CalendarClock, CircleDot, Mail, Plus, Send, TimerReset } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/page-header";
import { StageBadge } from "@/components/stage-badge";
import { APPLICATION_STAGES } from "@/lib/types";
import { getIntegrationStatus, listApplications, listTasks, listThreads } from "@/lib/data";
import { dueBucket, formatDateTime } from "@/lib/time";

export default async function DashboardPage() {
  const [applications, tasks, threads, integration] = await Promise.all([listApplications(), listTasks(), listThreads(), getIntegrationStatus()]);
  const open = applications.filter((app) => !["Rejected", "Withdrawn"].includes(app.stage)); const due = tasks.filter((task) => task.status !== "completed" && dueBucket(task.dueAt) !== "upcoming");
  return <div className="space-y-8"><PageHeader title="Good morning" description="Here’s what needs your attention today." actions={<><Button variant="outline" asChild><Link href="/tasks/new"><Plus />Task</Link></Button><Button asChild><Link href="/applications/new"><Plus />Application</Link></Button></>} />
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={CircleDot} label="Active applications" value={open.length} note="Across your pipeline" /><Metric icon={TimerReset} label="Due or overdue" value={due.length} note="Follow-ups and preparation" tone={due.length ? "amber" : "green"} /><Metric icon={Mail} label="Unread conversations" value={threads.filter((thread) => thread.unread).length} note={integration.connected ? "From connected Gmail" : "Gmail not connected"} /><Metric icon={CalendarClock} label="Interviews" value={applications.filter((app) => app.stage === "Interview").length} note="Upcoming pipeline stage" /></section>
    <section className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Application pipeline</CardTitle><Button variant="ghost" size="sm" asChild><Link href="/applications">View all <ArrowRight /></Link></Button></CardHeader><CardContent><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 xl:grid-cols-7">{APPLICATION_STAGES.map((stage) => <div key={stage} className="rounded-xl bg-muted/65 p-3"><StageBadge stage={stage} /><div className="mt-4 text-2xl font-semibold">{applications.filter((app) => app.stage === stage).length}</div></div>)}</div><div className="mt-5 divide-y">{applications.slice(0, 4).map((app) => <Link key={app.id} href={`/applications/${app.id}`} className="flex items-center justify-between gap-4 py-3 hover:text-primary"><div className="min-w-0"><p className="truncate font-medium">{app.role}</p><p className="text-sm text-muted-foreground">{app.company}</p></div><StageBadge stage={app.stage} /></Link>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Today & overdue</CardTitle></CardHeader><CardContent className="space-y-3">{due.length ? due.map((task) => <div key={task.id} className="rounded-xl border bg-white p-3"><div className="flex items-start justify-between gap-3"><p className="font-medium">{task.title}</p><Badge variant={dueBucket(task.dueAt) === "overdue" ? "destructive" : "default"}>{dueBucket(task.dueAt)}</Badge></div><p className="mt-2 text-xs text-muted-foreground">{task.applicationLabel ?? "General task"} · {formatDateTime(task.dueAt)}</p></div>) : <p className="text-sm text-muted-foreground">Nothing due today.</p>}</CardContent></Card></section>
    <section className="grid gap-6 lg:grid-cols-2"><Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Recent job-related messages</CardTitle><Button variant="ghost" size="sm" asChild><Link href="/email">Inbox <ArrowRight /></Link></Button></CardHeader><CardContent className="divide-y">{threads.slice(0, 4).map((thread) => <div key={thread.id} className="py-3"><div className="flex items-center gap-2"><p className="font-medium">{thread.subject}</p>{thread.unread ? <span className="size-2 rounded-full bg-primary" aria-label="Unread" /> : null}</div><p className="mt-1 line-clamp-1 text-sm text-muted-foreground">{thread.snippet}</p><p className="mt-2 text-xs text-muted-foreground">{formatDateTime(thread.lastMessageAt)}</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Mailbox status</CardTitle></CardHeader><CardContent><div className="flex items-center justify-between rounded-xl bg-muted p-4"><div><p className="font-medium">Gmail</p><p className="mt-1 text-sm text-muted-foreground">{integration.coverage}</p></div><Badge variant={integration.connected ? "default" : "outline"}>{integration.connected ? "Connected" : "Disconnected"}</Badge></div><p className="mt-4 text-sm text-muted-foreground">Last successful sync: {integration.lastSuccessfulSyncAt ? formatDateTime(integration.lastSuccessfulSyncAt) : "Never"}</p><Button className="mt-5" variant="outline" asChild><Link href="/settings#gmail"><Send />Manage connection</Link></Button></CardContent></Card></section>
  </div>;
}
function Metric({ icon: Icon, label, value, note, tone = "green" }: { icon: typeof Mail; label: string; value: number; note: string; tone?: "green" | "amber" }) { return <Card><CardContent className="p-5"><div className={`mb-5 grid size-9 place-items-center rounded-lg ${tone === "amber" ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-700"}`}><Icon className="size-4" /></div><div className="text-3xl font-semibold">{value}</div><div className="mt-1 text-sm font-medium">{label}</div><div className="mt-1 text-xs text-muted-foreground">{note}</div></CardContent></Card>; }
