import { createHash, randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireApiViewer } from "@/lib/auth";
import { createSupabaseServerClient } from "@/lib/supabase/server";

const MAX_SIZE = 10 * 1024 * 1024;
const allowed = new Set(["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"]);
function extension(type: string) { return type === "application/pdf" ? "pdf" : "docx"; }
function hasExpectedMagic(buffer: Buffer, type: string) { return type === "application/pdf" ? buffer.subarray(0, 5).toString() === "%PDF-" : buffer[0] === 0x50 && buffer[1] === 0x4b; }

export async function POST(request: Request) { const viewer = await requireApiViewer(); const form = await request.formData(); const file = form.get("file"); const label = z.string().trim().min(1).max(100).safeParse(form.get("label")); if (!(file instanceof File) || !label.success) return NextResponse.json({ error: "A file and version label are required." }, { status: 400 }); if (!allowed.has(file.type) || file.size < 1 || file.size > MAX_SIZE) return NextResponse.json({ error: "Use a PDF or DOCX file up to 10 MB." }, { status: 415 }); const buffer = Buffer.from(await file.arrayBuffer()); if (!hasExpectedMagic(buffer, file.type)) return NextResponse.json({ error: "The file content does not match its declared type." }, { status: 415 }); const supabase = await createSupabaseServerClient(); const path = `${viewer.id}/${randomUUID()}.${extension(file.type)}`; const uploaded = await supabase.storage.from("resumes").upload(path, buffer, { contentType: file.type, upsert: false }); if (uploaded.error) return NextResponse.json({ error: "Resume upload failed." }, { status: 500 }); const hash = createHash("sha256").update(buffer).digest("hex"); const { data: fileRow, error: fileError } = await supabase.from("resume_files").insert({ owner_id: viewer.id, storage_path: path, original_filename: file.name.slice(0, 240), mime_type: file.type, size_bytes: file.size, sha256: hash }).select("id").single(); if (fileError) { await supabase.storage.from("resumes").remove([path]); return NextResponse.json({ error: "Resume metadata could not be saved." }, { status: 500 }); } const { data: versions } = await supabase.from("resume_versions").select("version_number").eq("owner_id", viewer.id).eq("label", label.data).order("version_number", { ascending: false }).limit(1); const versionNumber = (versions?.[0]?.version_number ?? 0) + 1; const saved = await supabase.from("resume_versions").insert({ owner_id: viewer.id, resume_file_id: fileRow.id, label: label.data, version_number: versionNumber }).select("id,label,version_number").single(); if (saved.error) return NextResponse.json({ error: "Resume version could not be saved." }, { status: 500 }); return NextResponse.json(saved.data, { status: 201 }); }
