import Link from "next/link";
import { ExternalLink, MailPlus, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/page-header";
import { SyncButton } from "@/components/sync-button";
import { getIntegrationStatus, getThreadDetail, listThreads } from "@/lib/data";
import { emailWindowStart } from "@/lib/email/window";
import { formatDateTime } from "@/lib/time";
export default async function EmailPage({ searchParams }: { searchParams: Promise<{ q?: string; thread?: string }> }) {
  const params = await searchParams;
  const [threads, status, loadedDetail] = await Promise.all([listThreads(), getIntegrationStatus(), params.thread ? getThreadDetail(params.thread) : Promise.resolve(null)]);
  const detail = loadedDetail && loadedDetail.thread.lastMessageAt >= emailWindowStart() ? loadedDetail : null;
  const shown = threads.filter((thread) => !params.q || `${thread.subject} ${thread.snippet} ${thread.participants.join(" ")}`.toLowerCase().includes(params.q.toLowerCase()));
  return <div className="space-y-7"><PageHeader title="Recent email" description="Latest 50 conversations from the last 3 days. Older mail is available in Gmail." actions={<><SyncButton disabled={!status.connected} /><Button asChild><Link href="/email/compose"><MailPlus />Compose</Link></Button></>} />
    <div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Card className="overflow-hidden"><div className="border-b p-4"><form className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input aria-label="Search recent conversations" name="q" defaultValue={params.q} className="pl-9" placeholder="Search recent conversations" /></form></div><div className="max-h-[700px] divide-y overflow-y-auto">{shown.length === 0 ? <p className="p-6 text-sm text-muted-foreground">{status.connected ? "No recent conversations. Sync Gmail to refresh the last 3 days." : "Connect Gmail in Settings to load recent email."}</p> : shown.map((thread) => <Link key={thread.id} href={{ pathname: "/email", query: { thread: thread.id, ...(params.q ? { q: params.q } : {}) } }} className={`block p-4 hover:bg-muted/50 ${detail?.thread.id === thread.id ? "bg-primary/5" : ""}`}><div className="flex items-start justify-between gap-3"><p className="font-medium">{thread.subject}</p>{thread.unread ? <span className="mt-2 size-2 shrink-0 rounded-full bg-primary" aria-label="Unread" /> : null}</div><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{thread.snippet}</p><p className="mt-3 text-xs text-muted-foreground">{formatDateTime(thread.lastMessageAt)}</p></Link>)}</div></Card>
      <Card><CardContent className={detail ? "min-h-[560px] p-6" : "grid min-h-[560px] place-items-center p-8 text-center"}>{detail ? <div><div className="flex flex-wrap items-start justify-between gap-4 border-b pb-5"><div><h2 className="text-xl font-semibold">{detail.thread.subject}</h2><p className="mt-1 text-sm text-muted-foreground">{detail.thread.participants.join(", ")}</p></div><div className="flex gap-2"><Button variant="outline" asChild><Link href={`/email/compose?thread=${detail.thread.id}`}><MailPlus />Reply</Link></Button>{detail.gmailPermalink ? <Button variant="ghost" asChild><a href={detail.gmailPermalink} target="_blank" rel="noreferrer"><ExternalLink />Gmail</a></Button> : null}</div></div><div className="mt-5 space-y-4">{detail.messages.map((message) => <article key={message.id} className={`rounded-xl border p-4 ${message.direction === "outgoing" ? "ml-4 bg-emerald-50/50" : "mr-4 bg-white"}`}><div className="flex flex-wrap justify-between gap-2 text-xs text-muted-foreground"><span>{message.direction === "outgoing" ? "You" : message.from} → {message.to.join(", ")}</span><time>{formatDateTime(message.sentAt)}</time></div><div className="mt-3 whitespace-pre-wrap break-words text-sm leading-7">{message.bodyText || "(No plain-text body)"}</div></article>)}</div></div> : <div><h2 className="font-semibold">Select a recent conversation</h2><p className="mt-2 text-sm text-muted-foreground">Review the conversation and write a reply.</p><Badge variant={status.connected ? "default" : "outline"} className="mt-5">Gmail {status.connected ? "connected" : "disconnected"}</Badge></div>}</CardContent></Card>
    </div></div>;
}
