import Link from "next/link";
import { LayoutGrid, List, Plus, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/page-header";
import { StageBadge } from "@/components/stage-badge";
import { Card } from "@/components/ui/card";
import { APPLICATION_STAGES } from "@/lib/types";
import { listApplications } from "@/lib/data";
import { formatDateTime } from "@/lib/time";

export default async function ApplicationsPage({ searchParams }: { searchParams: Promise<{ view?: string; q?: string; stage?: string }> }) {
  const params = await searchParams; const view = params.view === "kanban" ? "kanban" : "table"; const query = params.q?.toLowerCase() ?? "";
  const applications = (await listApplications()).filter((app) => (!query || `${app.role} ${app.company} ${app.contactName ?? ""}`.toLowerCase().includes(query)) && (!params.stage || app.stage === params.stage));
  return <div className="space-y-7"><PageHeader title="Applications" description="Track every opportunity from first save to final decision." actions={<Button asChild><Link href="/applications/new"><Plus />Add application</Link></Button>} />
    <Card className="p-4"><form className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input name="q" defaultValue={params.q} className="pl-9" placeholder="Search role, company, or contact" /></div><select name="stage" defaultValue={params.stage ?? ""} className="h-10 rounded-lg border bg-background px-3 text-sm"><option value="">All stages</option>{APPLICATION_STAGES.map((stage) => <option key={stage}>{stage}</option>)}</select><input type="hidden" name="view" value={view} /><Button type="submit" variant="secondary">Filter</Button><div className="flex rounded-lg border p-1"><Button asChild size="sm" variant={view === "table" ? "secondary" : "ghost"}><Link href={{ query: { ...params, view: "table" } }} aria-label="Table view"><List /></Link></Button><Button asChild size="sm" variant={view === "kanban" ? "secondary" : "ghost"}><Link href={{ query: { ...params, view: "kanban" } }} aria-label="Kanban view"><LayoutGrid /></Link></Button></div></form></Card>
    {view === "kanban" ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{APPLICATION_STAGES.map((stage) => <section key={stage} className="rounded-2xl bg-muted/70 p-3"><div className="mb-3 flex items-center justify-between"><StageBadge stage={stage} /><span className="text-sm text-muted-foreground">{applications.filter((app) => app.stage === stage).length}</span></div><div className="space-y-3">{applications.filter((app) => app.stage === stage).map((app) => <Link key={app.id} href={`/applications/${app.id}`} className="block rounded-xl border bg-white p-4 shadow-sm hover:border-primary/50"><p className="font-medium">{app.role}</p><p className="mt-1 text-sm text-muted-foreground">{app.company}</p>{app.nextAction ? <p className="mt-4 text-xs text-muted-foreground">Next: {app.nextAction}</p> : null}</Link>)}</div></section>)}</div> : <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/50 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-3">Role & company</th><th className="px-5 py-3">Stage</th><th className="px-5 py-3">Priority</th><th className="px-5 py-3">Applied</th><th className="px-5 py-3">Next action</th></tr></thead><tbody className="divide-y">{applications.map((app) => <tr key={app.id} className="hover:bg-muted/35"><td className="px-5 py-4"><Link href={`/applications/${app.id}`} className="font-medium hover:text-primary">{app.role}</Link><div className="text-muted-foreground">{app.company}{app.location ? ` · ${app.location}` : ""}</div></td><td className="px-5 py-4"><StageBadge stage={app.stage} /></td><td className="px-5 py-4">{app.priority}</td><td className="px-5 py-4 text-muted-foreground">{app.appliedAt ? formatDateTime(app.appliedAt) : "Not yet"}</td><td className="px-5 py-4"><div>{app.nextAction ?? "—"}</div>{app.nextActionAt ? <div className="text-xs text-muted-foreground">{formatDateTime(app.nextActionAt)}</div> : null}</td></tr>)}</tbody></table></div></Card>}
  </div>;
}
