import { BrainCircuit, Download, LockKeyhole, Mail, Upload } from "lucide-react";
import { logout } from "@/app/login/actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { ResumeUploader } from "@/components/resume-uploader";
import { Label } from "@/components/ui/label";
import { PageHeader } from "@/components/page-header";
import { Textarea } from "@/components/ui/textarea";
import { getIntegrationStatus } from "@/lib/data";
import { requireViewer } from "@/lib/auth";
import { serverEnv } from "@/lib/env";
const gmailErrors: Record<string, string> = { server_config: "Gmail could not be saved: set a real SUPABASE_SERVICE_ROLE_KEY in .env.local and restart the app.", encryption: "Set OAUTH_TOKEN_ENCRYPTION_KEY to a base64-encoded 32-byte key and restart the app.", google: "Google authorization failed. Check your OAuth credentials, redirect URI, and Gmail API access, then reconnect.", database: "Could not save the Gmail connection. Check the Supabase server key and apply the database migration.", credential: "Could not save Gmail offline access. Check the credential migration functions and reconnect with Google consent." };
export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ gmail?: string; gmail_error?: string }> }) { const query = await searchParams; const [viewer, integration] = await Promise.all([requireViewer(), getIntegrationStatus()]); return <div className="space-y-7"><PageHeader title="Profile & settings" description="Control the facts used in applications, reminders, email, and AI drafts." /><div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Professional profile</CardTitle><CardDescription>AI drafts may use only the selected facts from this profile.</CardDescription></CardHeader><CardContent className="space-y-4"><Field label="Name" placeholder="Your name" /><div className="space-y-2"><Label htmlFor="summary">Professional summary</Label><Textarea id="summary" placeholder="A concise factual summary" /></div><Field label="Skills" placeholder="Product design, research, prototyping" /><Field label="Portfolio URL" type="url" placeholder="https://…" /><Button disabled={viewer.demo}>Save profile</Button></CardContent></Card><Card><CardHeader><CardTitle>Preferences</CardTitle></CardHeader><CardContent className="space-y-4"><Field label="Timezone" defaultValue="Asia/Karachi" /><Field label="Preferred writing tone" defaultValue="Professional, warm, and concise" /><div className="space-y-2"><Label htmlFor="signature">Email signature</Label><Textarea id="signature" /></div><Button disabled={viewer.demo}>Save preferences</Button></CardContent></Card>
      <Card id="gmail">{query.gmail === "error" ? <p role="alert" className="mx-6 mt-6 rounded-lg bg-red-50 p-3 text-sm text-red-700">{gmailErrors[query.gmail_error ?? ""] ?? "Gmail connection failed. Check your configuration and reconnect."}</p> : null}{query.gmail === "connected" && integration.connected ? <p role="status" className="mx-6 mt-6 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Gmail connection saved. Open Email and sync your conversations.</p> : null}<CardHeader><div className="flex items-center gap-2"><Mail className="size-5 text-primary" /><CardTitle>Gmail connection</CardTitle></div><CardDescription>CRM login and Gmail authorization are separate capabilities.</CardDescription></CardHeader><CardContent><div className="flex items-center justify-between rounded-xl bg-muted p-4"><div><p className="font-medium">{viewer.email}</p><p className="text-sm text-muted-foreground">Scopes: read-only mail + send</p></div><Badge variant={integration.connected ? "default" : "outline"}>{integration.connected ? "Connected" : "Disconnected"}</Badge></div><div className="mt-5 flex gap-2">{integration.connected ? <><Button variant="outline" asChild><a href="/api/gmail/oauth/start">Reconnect</a></Button><Button variant="outline" className="text-destructive" disabled={viewer.demo}>Disconnect</Button></> : <Button asChild={!viewer.demo} disabled={viewer.demo}>{viewer.demo ? "Configure credentials first" : <a href="/api/gmail/oauth/start">Connect Gmail</a>}</Button>}</div></CardContent></Card>
      <Card><CardHeader><div className="flex items-center gap-2"><Upload className="size-5 text-primary" /><CardTitle>Resume versions</CardTitle></div><CardDescription>Files use a private bucket and short-lived download links.</CardDescription></CardHeader><CardContent><ResumeUploader disabled={viewer.demo} /></CardContent></Card><Card><CardHeader><div className="flex items-center gap-2"><BrainCircuit className="size-5 text-primary" /><CardTitle>AI configuration</CardTitle></div></CardHeader><CardContent><div className="flex items-center justify-between rounded-xl bg-muted p-4"><div><p className="font-medium">OpenAI Responses API</p><p className="text-sm text-muted-foreground">Model: {serverEnv.openAiModel}</p></div><Badge variant={serverEnv.openAiKey ? "default" : "outline"}>{serverEnv.openAiKey ? "Configured" : "Not configured"}</Badge></div><p className="mt-4 text-sm text-muted-foreground">Draft context can include your profile, the selected application and job description, and the selected conversation. Unrelated mailbox content and attachments are excluded.</p></CardContent></Card>
      <Card><CardHeader><div className="flex items-center gap-2"><Download className="size-5 text-primary" /><CardTitle>Data & access</CardTitle></div></CardHeader><CardContent className="space-y-4"><Button variant="outline" asChild={!viewer.demo} disabled={viewer.demo}>{viewer.demo ? "CSV export unavailable in sample mode" : <a href="/api/export/applications"><Download />Export applications CSV</a>}</Button><div className="flex items-center gap-2 text-xs text-muted-foreground"><LockKeyhole className="size-4" />Owner-only access is checked in route handlers and RLS.</div><form action={logout}><Button variant="outline">Sign out</Button></form></CardContent></Card></div></div>; }
function Field({ label, ...props }: { label: string } & React.ComponentProps<typeof Input>) { const id = label.toLowerCase().replaceAll(" ", "-"); return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Input id={id} {...props} /></div>; }
