import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requireApiViewer } from "@/lib/auth";
import { composeMime } from "@/lib/email/mime";
import { prepareTracking } from "@/lib/email/tracking";
import { gmailForAccount, isAmbiguousSendError, requestFingerprint } from "@/lib/email/gmail";
import { enforceRateLimit } from "@/lib/security/rate-limit";
import { createSupabaseServerClient } from "@/lib/supabase/server";

const attachmentSchema = z.object({ filename: z.string().min(1).max(240), contentType: z.enum(["application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","image/png","image/jpeg"]), contentBase64: z.string().min(1) });
const sendSchema = z.object({ to: z.array(z.email()).min(1).max(20), cc: z.array(z.email()).max(20).default([]), bcc: z.array(z.email()).max(20).default([]), subject: z.string().trim().min(1).max(998), bodyText: z.string().min(1).max(100000), attachments: z.array(attachmentSchema).max(5).default([]), threadId: z.string().max(200).optional(), inReplyTo: z.string().max(998).optional(), references: z.array(z.string().max(998)).max(50).optional(), replyTo: z.email().optional(), applicationId: z.uuid().nullable().optional() });

export async function POST(request: NextRequest) {
  const viewer = await requireApiViewer(); const idempotencyKey = request.headers.get("idempotency-key"); if (!idempotencyKey || idempotencyKey.length > 200) return NextResponse.json({ error: "A valid idempotency key is required." }, { status: 400 });
  const parsed = sendSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message }, { status: 400 });
  const attachments = parsed.data.attachments.map((item) => ({ ...item, content: Buffer.from(item.contentBase64, "base64") })); const totalSize = attachments.reduce((sum, item) => sum + item.content.length, 0); if (totalSize > 3 * 1024 * 1024) return NextResponse.json({ error: "Attachments must total 3 MB or less." }, { status: 413 });
  await enforceRateLimit(viewer.id, "email_send", 20, 1); const supabase = await createSupabaseServerClient(); const { data: account, error: accountError } = await supabase.from("email_accounts").select("id,email_address,status").eq("provider", "gmail").single(); if (accountError || account.status !== "connected") return NextResponse.json({ error: "Connect Gmail before sending." }, { status: 409 });
  const fingerprint = requestFingerprint(parsed.data); const tracking = prepareTracking(parsed.data.bodyText); const inserted = await supabase.from("outbound_send_attempts").insert({ owner_id: viewer.id, email_account_id: account.id, idempotency_key: idempotencyKey, request_fingerprint: fingerprint, status: "sending", started_at: new Date().toISOString(), to_addresses: parsed.data.to, subject: parsed.data.subject, tracking_token: tracking.token }).select("id,status").single();
  if (inserted.error) { const { data: existing } = await supabase.from("outbound_send_attempts").select("id,status,request_fingerprint,provider_message_id,provider_thread_id").eq("email_account_id", account.id).eq("idempotency_key", idempotencyKey).single(); if (!existing || existing.request_fingerprint !== fingerprint) return NextResponse.json({ error: "Idempotency key conflict." }, { status: 409 }); return NextResponse.json({ status: existing.status, messageId: existing.provider_message_id, threadId: existing.provider_thread_id }, { status: existing.status === "sent" ? 200 : 409 }); }
  try { const raw = await composeMime({ from: account.email_address, to: parsed.data.to, cc: parsed.data.cc, bcc: parsed.data.bcc, subject: parsed.data.subject, bodyText: parsed.data.bodyText, html: tracking.html, inReplyTo: parsed.data.inReplyTo, references: parsed.data.references, replyTo: parsed.data.replyTo, attachments: attachments.map((item) => ({ filename: item.filename, contentType: item.contentType, content: item.content })) }); const gmail = await gmailForAccount(account.id, viewer.id); const sent = await gmail.users.messages.send({ userId: "me", requestBody: { raw, threadId: parsed.data.threadId } }, { retry: false, timeout: 30_000 }); await supabase.from("outbound_send_attempts").update({ status: "sent", provider_message_id: sent.data.id ?? null, provider_thread_id: sent.data.threadId ?? null, finished_at: new Date().toISOString() }).eq("id", inserted.data.id); return NextResponse.json({ status: "sent", messageId: sent.data.id, threadId: sent.data.threadId }); }
  catch (error) { const uncertain = isAmbiguousSendError(error); await supabase.from("outbound_send_attempts").update({ status: uncertain ? "uncertain" : "failed", error_code: uncertain ? "DELIVERY_UNKNOWN" : "PROVIDER_REJECTED", safe_error_message: uncertain ? "Provider response was not received." : "Gmail rejected the send request.", finished_at: new Date().toISOString() }).eq("id", inserted.data.id); return NextResponse.json({ status: uncertain ? "uncertain" : "failed", error: uncertain ? "Delivery result is uncertain; reconciliation is required before retry." : "Gmail could not send this message." }, { status: uncertain ? 409 : 502 }); }
}