import Link from "next/link";
import { ArrowLeft, FileText, MailPlus, UserRound } from "lucide-react";
import { notFound } from "next/navigation";
import { DestructiveActions } from "@/app/(app)/applications/[id]/destructive-actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { StageBadge } from "@/components/stage-badge";
import { getApplication, listApplications } from "@/lib/data";
import { requireViewer } from "@/lib/auth";
import { formatDateTime } from "@/lib/time";

export default async function ApplicationDetailPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const [raw, apps, viewer] = await Promise.all([getApplication(id), listApplications(), requireViewer()]); const app = apps.find((item) => item.id === id); if (!raw || !app) notFound(); return <div className="space-y-7"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div><Button variant="ghost" size="sm" asChild className="-ml-3 mb-3"><Link href="/applications"><ArrowLeft />Applications</Link></Button><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold tracking-tight">{app.role}</h1><StageBadge stage={app.stage} /></div><p className="mt-2 text-lg text-muted-foreground">{app.company}{app.location ? ` · ${app.location}` : ""}{app.workArrangement ? ` · ${app.workArrangement}` : ""}</p></div><div className="flex flex-wrap gap-2"><Button asChild><Link href={`/email/compose?application=${app.id}`}><MailPlus />Compose email</Link></Button><DestructiveActions id={app.id} disabled={viewer.demo} /></div></div>
    <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><div className="space-y-6"><Card><CardHeader><CardTitle>Application overview</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Detail label="Saved" value={formatDateTime(app.savedAt)} /><Detail label="Applied" value={app.appliedAt ? formatDateTime(app.appliedAt) : "Not yet"} /><Detail label="Priority" value={app.priority} /><Detail label="Next action" value={app.nextAction ?? "No task scheduled"} /></CardContent></Card><Card><CardHeader><CardTitle>Job description & notes</CardTitle></CardHeader><CardContent><div className="rounded-xl bg-muted p-5 text-sm leading-7 text-muted-foreground"><FileText className="mb-3 size-5" />Add or edit the full job description and private notes after connecting Supabase. Long content is kept in this scrollable section.</div></CardContent></Card><Card><CardHeader><CardTitle>Activity</CardTitle></CardHeader><CardContent><div className="border-l-2 pl-4 text-sm"><p className="font-medium">Application saved</p><p className="text-muted-foreground">{formatDateTime(app.savedAt)}</p></div></CardContent></Card></div><aside className="space-y-6"><Card><CardHeader><CardTitle>Contacts</CardTitle></CardHeader><CardContent>{app.contactName ? <div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-muted"><UserRound className="size-4" /></div><div><p className="font-medium">{app.contactName}</p><p className="text-sm text-muted-foreground">Recruiter contact</p></div></div> : <p className="text-sm text-muted-foreground">No contact linked.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Resume version</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">No resume version linked.</p></CardContent></Card><Card><CardHeader><CardTitle>Linked conversations</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Manual and suggested associations appear here.</p></CardContent></Card></aside></div>
  </div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</div><div className="mt-1 font-medium">{value}</div></div>; }
